<a href="https://colab.research.google.com/github/samreenfathima18/guvi-project/blob/main/project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Project Title-Uber Eats Bangalore Restaurant Intelligence & Decision Support Systems**





---

In [ ]:
import pandas as pd
import numpy as np

**Step 1: Read the csv file using pandas**

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Uber_Eats_data.csv")

***Displays the total no.of rows and columns present in the given data set***

In [ ]:
df.shape

(23193, 13)

**Displays the column names of the given data set**

In [ ]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'listed_in(type)', 'listed_in(city)'],
      dtype='object')

**Displays the first few rows of the given data set**

In [ ]:
df.head()

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),listed_in(type),listed_in(city)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari

**Summary of a DataFrame**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23193 entries, 0 to 23192
Data columns (total 13 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         23193 non-null  object
 1   online_order                 23193 non-null  object
 2   book_table                   23193 non-null  object
 3   rate                         23193 non-null  object
 4   votes                        23193 non-null  int64
 5   phone                        23193 non-null  object
 6   location                     23193 non-null  object
 7   rest_type                    23193 non-null  object
 8   dish_liked                   23193 non-null  object
 9   cuisines                     23193 non-null  object
 10  approx_cost(for two people)  23193 non-null  object
 11  listed_in(type)              23193 non-null  object
 12  listed_in(city)              23193 non-null  object
dtypes: int64(1), object(12)
memory usage: 2.3+ MB

**Step 2: Check for Null Values**

In [ ]:
print(df.isnull().sum())

name                           0
online_order                   0
book_table                     0
rate                           0
votes                          0
phone                          0
location                       0
rest_type                      0
dish_liked                     0
cuisines                       0
approx_cost(for two people)    0
listed_in(type)                0
listed_in(city)                0
dtype: int64

**Renaming columns of the given dataset**

In [ ]:
df.columns = ['name', 'online_order', 'book_table', 'rate', 'votes',
              'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
              'cost_2_pax', 'type', 'city']

In [ ]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_2_pax,type,city
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

**Step3:Knowing and removing the duplicates from the data set**

In [ ]:
df.duplicated().sum()

np.int64(35)

*** permanent removal of all identical rows from the dataset***

In [ ]:
df.drop_duplicates(inplace=True)
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_2_pax,type,city
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8 /5,128,+91 7625087121\n+91 8050587483,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9 /5,77,080 49435000,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield
23190,Keys Cafe - Keys Hotel,No,No,2.8 /5,161,080 39451000\n+91 8884038484,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield
23191,Bhagini,No,No,2.5 /5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield

missing values in every column of your DataFrame.

---



---

In [ ]:
df['name']

0                                                    Jalsa
1                                           Spice Elephant
2                                          San Churro Cafe
3                                    Addhuri Udupi Bhojana
4                                            Grand Village
                               ...
23188                                   Izakaya Gastro Pub
23189          M Bar - Bengaluru Marriott Hotel Whitefield
23190                               Keys Cafe - Keys Hotel
23191                                              Bhagini
23192    Chime - Sheraton Grand Bengaluru Whitefield Ho...
Name: name, Length: 23158, dtype: object

**To know the count of unique values in a particular column**

In [ ]:
df['online_order'].value_counts()

online_order
Yes    16335
No      6823
Name: count, dtype: int64

In [ ]:
df['rate']

0         4.1/5
1         4.1/5
2         3.8/5
3         3.7/5
4         3.8/5
          ...
23188    3.8 /5
23189    3.9 /5
23190    2.8 /5
23191    2.5 /5
23192    4.3 /5
Name: rate, Length: 23158, dtype: object

In [ ]:
df['rate'] = df['rate'].str.replace('/5', '').str.strip()

In [ ]:
df['rate'] = pd.to_numeric(df['rate'], errors='coerce')

In [ ]:
print(df['rate'].head())

0    4.1
1    4.1
2    3.8
3    3.7
4    3.8
Name: rate, dtype: float64

In [ ]:
df.rate.isnull().sum()

np.int64(146)

In [ ]:
df.describe()

               rate         votes
count  23012.000000  23158.000000
mean       3.904002    600.290137
std        0.426388   1114.238551
min        1.800000      0.000000
25%        3.800000    101.000000
50%        4.000000    221.000000
75%        4.200000    584.750000
max        4.900000  16832.000000

**Step4: Filling the Null values**

In [ ]:
df['rate'] = df['rate'].fillna(df['rate'].median())

In [ ]:
df.rate.isnull().sum()

np.int64(0)

In [ ]:
df['phone']

0          080 42297555\r\n+91 9743772233
1                            080 41714161
2                          +91 9663487993
3                          +91 9620009302
4        +91 8026612447\r\n+91 9901210005
                       ...
23188      +91 7625087121\n+91 8050587483
23189                        080 49435000
23190        080 39451000\n+91 8884038484
23191                        080 65951222
23192                        080 49652769
Name: phone, Length: 23158, dtype: object

In [ ]:
df[['Primary_Phone', 'Secondary_Phone']] = df['phone'].str.split(r'\r\n|\n',expand=True)

In [ ]:
for col in ['Primary_Phone']:
    # Remove everything except digits and the + sign
    df[col] = df[col].str.replace(r'[^\d+]', '', regex=True)

In [ ]:
df['Primary_Phone']

0          08042297555
1          08041714161
2        +919663487993
3        +919620009302
4        +918026612447
             ...
23188    +917625087121
23189      08049435000
23190      08039451000
23191      08065951222
23192      08049652769
Name: Primary_Phone, Length: 23158, dtype: object

In [ ]:
#df['Primary_Phone'] = df['Primary_Phone'].str.replace(' ', '', regex=False)
#df['Secondary_Phone'] = df['Secondary_Phone'].str.replace(' ', '', regex=False)

In [ ]:
df = df.drop('phone', axis=1)

In [ ]:
newdata=df = df.drop('Secondary_Phone', axis=1)

In [ ]:
df.Primary_Phone.isnull().sum()

np.int64(0)

In [ ]:
df

,name,online_order,book_table,rate,votes,location,rest_type,dish_liked,cuisines,cost_2_pax,type,city,Primary_Phone
0,Jalsa,Yes,Yes,4.1,775,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,Buffet,Banashankari,08042297555
1,Spice Elephant,Yes,No,4.1,787,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,Buffet,Banashankari,08041714161
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,Buffet,Banashankari,+919663487993
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,Buffet,Banashankari,+919620009302
4,Grand Village,No,No,3.8,166,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,Buffet,Banashankari,+918026612447
...,...,...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,Whitefield,"Bar, Casual Dining","Beer, Chicken Guntur, Paneer Tikka, Fish, Nood...","North Indian, Continental, Mediterranean","1,200",Pubs and bars,Whitefield,+917625087121
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,Whitefield,"Fine Dining, Bar",Rooftop Ambience,Finger Food,"2,000",Pubs and bars,Whitefield,08049435000
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,Whitefield,"Casual Dining, Bar","Salads, Coffee, Breakfast Buffet, Halwa, Chick...","Chinese, Continental, North Indian","1,200",Pubs and bars,Whitefield,08039451000
23191,Bhagini,No,No,2.5,81,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield,08065951222
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500",Pubs and bars,Whitefield,08049652769

In [ ]:
df['votes']

0        775
1        787
2        918
3         88
4        166
        ...
23188    128
23189     77
23190    161
23191     81
23192    236
Name: votes, Length: 23158, dtype: int64

In [ ]:
df.votes.isnull().sum()

np.int64(0)

In [ ]:
df['location']

0                      Banashankari
1                      Banashankari
2                      Banashankari
3                      Banashankari
4                      Basavanagudi
                    ...
23188                    Whitefield
23189                    Whitefield
23190                    Whitefield
23191                    Whitefield
23192    ITPL Main Road, Whitefield
Name: location, Length: 23158, dtype: object

In [ ]:
df.location.isnull().sum()

np.int64(0)

In [ ]:
#df['rest_type']

In [ ]:
a=df = df.drop('rest_type', axis=1)

In [ ]:
df['cost_2_pax']

0          800
1          800
2          800
3          300
4          600
         ...
23188    1,200
23189    2,000
23190    1,200
23191      800
23192    2,500
Name: cost_2_pax, Length: 23158, dtype: object

In [ ]:
df['cost_2_pax'] = df['cost_2_pax'].str.replace(',', '')

In [ ]:
df['cost_2_pax'] = df['cost_2_pax'].astype(int)

In [ ]:
df['cost_2_pax'] = pd.to_numeric(df['cost_2_pax'],errors='coerce')

In [ ]:
df['cost_2_pax'].isnull().sum()

np.int64(0)

In [ ]:
print(df.dtypes)

name              object
online_order      object
book_table        object
rate             float64
votes              int64
location          object
dish_liked        object
cuisines          object
cost_2_pax         int64
type              object
city              object
Primary_Phone     object
dtype: object

In [ ]:
df['dish_liked'].head(10)

0    Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1    Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2    Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                          Masala Dosa
4                                  Panipuri, Gol Gappe
5    Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...
6    Farmhouse Pizza, Chocolate Banana, Virgin Moji...
7    Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...
8    Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...
9    Waffles, Pasta, Crispy Chicken, Honey Chilli C...
Name: dish_liked, dtype: object

In [ ]:
b=df = df.drop('dish_liked', axis=1)

In [ ]:
df

,name,online_order,book_table,rate,votes,location,cuisines,cost_2_pax,type,city,Primary_Phone
0,Jalsa,Yes,Yes,4.1,775,Banashankari,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari,08042297555
1,Spice Elephant,Yes,No,4.1,787,Banashankari,"Chinese, North Indian, Thai",800,Buffet,Banashankari,08041714161
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Mexican, Italian",800,Buffet,Banashankari,+919663487993
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,"South Indian, North Indian",300,Buffet,Banashankari,+919620009302
4,Grand Village,No,No,3.8,166,Basavanagudi,"North Indian, Rajasthani",600,Buffet,Banashankari,+918026612447
...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,Whitefield,"North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield,+917625087121
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,Whitefield,Finger Food,2000,Pubs and bars,Whitefield,08049435000
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,Whitefield,"Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield,08039451000
23191,Bhagini,No,No,2.5,81,Whitefield,"Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield,08065951222
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Finger Food,2500,Pubs and bars,Whitefield,08049652769

In [ ]:
df['cuisines']

0                     North Indian, Mughlai, Chinese
1                        Chinese, North Indian, Thai
2                             Cafe, Mexican, Italian
3                         South Indian, North Indian
4                           North Indian, Rajasthani
                            ...
23188       North Indian, Continental, Mediterranean
23189                                    Finger Food
23190             Chinese, Continental, North Indian
23191    Andhra, South Indian, Chinese, North Indian
23192                                    Finger Food
Name: cuisines, Length: 23158, dtype: object

In [ ]:
df.cuisines.isnull().sum()

np.int64(0)

In [ ]:
df['cuisines'] = df['cuisines'].str.strip().str.title()

In [ ]:
#df['cuisines_list'] = df['cuisines'].apply(
   # lambda x: [i.strip().title() for i in str(x).split(',')] if pd.notnull(x) else ['Unknown']
#)

In [ ]:
df

,name,online_order,book_table,rate,votes,location,cuisines,cost_2_pax,type,city,Primary_Phone
0,Jalsa,Yes,Yes,4.1,775,Banashankari,"North Indian, Mughlai, Chinese",800,Buffet,Banashankari,08042297555
1,Spice Elephant,Yes,No,4.1,787,Banashankari,"Chinese, North Indian, Thai",800,Buffet,Banashankari,08041714161
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Mexican, Italian",800,Buffet,Banashankari,+919663487993
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,"South Indian, North Indian",300,Buffet,Banashankari,+919620009302
4,Grand Village,No,No,3.8,166,Basavanagudi,"North Indian, Rajasthani",600,Buffet,Banashankari,+918026612447
...,...,...,...,...,...,...,...,...,...,...,...
23188,Izakaya Gastro Pub,Yes,Yes,3.8,128,Whitefield,"North Indian, Continental, Mediterranean",1200,Pubs and bars,Whitefield,+917625087121
23189,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,Whitefield,Finger Food,2000,Pubs and bars,Whitefield,08049435000
23190,Keys Cafe - Keys Hotel,No,No,2.8,161,Whitefield,"Chinese, Continental, North Indian",1200,Pubs and bars,Whitefield,08039451000
23191,Bhagini,No,No,2.5,81,Whitefield,"Andhra, South Indian, Chinese, North Indian",800,Pubs and bars,Whitefield,08065951222
23192,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Finger Food,2500,Pubs and bars,Whitefield,08049652769

In [ ]:
df['type']

0               Buffet
1               Buffet
2               Buffet
3               Buffet
4               Buffet
             ...
23188    Pubs and bars
23189    Pubs and bars
23190    Pubs and bars
23191    Pubs and bars
23192    Pubs and bars
Name: type, Length: 23158, dtype: object

In [ ]:
df['type'].isnull().sum()

np.int64(0)

In [ ]:
d=df = df.drop('type', axis=1)

In [ ]:
e=df = df.drop('Primary_Phone', axis=1)

In [ ]:
df['city']

0        Banashankari
1        Banashankari
2        Banashankari
3        Banashankari
4        Banashankari
             ...
23188      Whitefield
23189      Whitefield
23190      Whitefield
23191      Whitefield
23192      Whitefield
Name: city, Length: 23158, dtype: object

In [ ]:
df['city'] = df['city'].str.strip()

In [ ]:
df['city'].isnull().sum()

np.int64(0)

In [ ]:
e=df = df.drop('city', axis=1)

In [ ]:
print(df.dtypes)

name             object
online_order     object
book_table       object
rate            float64
votes             int64
location         object
cuisines         object
cost_2_pax        int64
dtype: object

In [ ]:
df.columns = ['restaurant_name', 'online_order', 'book_table', 'rate','votes','location','cuisines',
              'approx_cost_for_two']

In [ ]:
df

,restaurant_name,online_order,book_table,rate,location,cuisines,approx_cost_for_two
0,Jalsa,Yes,Yes,4.1,Banashankari,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1,Banashankari,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8,Banashankari,"Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7,Banashankari,"South Indian, North Indian",300
4,Grand Village,No,No,3.8,Basavanagudi,"North Indian, Rajasthani",600
...,...,...,...,...,...,...,...
23153,Izakaya Gastro Pub,Yes,Yes,3.8,Whitefield,"North Indian, Continental, Mediterranean",1200
23154,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,Whitefield,Finger Food,2000
23155,Keys Cafe - Keys Hotel,No,No,2.8,Whitefield,"Chinese, Continental, North Indian",1200
23156,Bhagini,No,No,2.5,Whitefield,"Andhra, South Indian, Chinese, North Indian",800
23157,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,"ITPL Main Road, Whitefield",Finger Food,2500

In [ ]:
from google.colab import files
df.to_csv('restaurantdata1.csv', index=False)
files.download('restaurantdata1.csv')

**INSERTING THE CLEANED DATA USING SQLITE3**

In [ ]:
import sqlite3

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/restaurantdata (1).csv')

In [ ]:
df

,restaurant_name,online_order,book_table,rate,votes,location,cuisines,approx_cost_for_two
0,Jalsa,Yes,Yes,4.1,775,Banashankari,"North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1,787,Banashankari,"Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8,918,Banashankari,"Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7,88,Banashankari,"South Indian, North Indian",300
4,Grand Village,No,No,3.8,166,Basavanagudi,"North Indian, Rajasthani",600
...,...,...,...,...,...,...,...,...
23153,Izakaya Gastro Pub,Yes,Yes,3.8,128,Whitefield,"North Indian, Continental, Mediterranean",1200
23154,M Bar - Bengaluru Marriott Hotel Whitefield,No,No,3.9,77,Whitefield,Finger Food,2000
23155,Keys Cafe - Keys Hotel,No,No,2.8,161,Whitefield,"Chinese, Continental, North Indian",1200
23156,Bhagini,No,No,2.5,81,Whitefield,"Andhra, South Indian, Chinese, North Indian",800
23157,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3,236,"ITPL Main Road, Whitefield",Finger Food,2500

**GIVING CONNECTION TO THE DATABASE**

In [ ]:
conn = sqlite3.connect('restaurant1.db')
cursor = conn.cursor()

**SQL COMMAND TO CREATE A TABLE**

In [ ]:
query= """
CREATE TABLE restaurants1 (
    restaurant_name VARCHAR(255),
    online_order VARCHAR(5),
    book_table VARCHAR(5),
    rate VARCHAR(10),
    votes INT,
    location VARCHAR(100),
    cuisines VARCHAR(255),
    approx_cost_for_two INT
);
"""
cursor.execute(query)

conn.commit()
print("Table created successfully!")

OperationalError: table restaurants1 already exists

**INSERTING THE DATA INTO THE TABLE**

In [ ]:
data_list = df.values.tolist()
insert_query = """ INSERT INTO restaurants1 (restaurant_name, online_order, book_table, rate,votes, location, cuisines, approx_cost_for_two)
VALUES (?, ?, ?, ?, ?, ?, ?,?);
"""
cursor.executemany(insert_query,data_list)
conn.commit()

In [ ]:
cursor.execute("SELECT COUNT(*) FROM restaurants1;")
count = cursor.fetchone()[0]

print(f"Total rows in table: {count}")

Total rows in table: 23158

In [ ]:
pip install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (0.9.0)

In [ ]:
from tabulate import tabulate

1.Which Bangalore locations have the highest average restaurant ratings?

In [ ]:
conn = sqlite3.connect('restaurant1.db')
query1 = """
SELECT
    location,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_restaurants,
    ROUND(AVG( approx_cost_for_two), 0) AS avg_cost
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY location
HAVING total_restaurants >=30
ORDER BY avg_rating DESC
LIMIT 10;
"""
premium_locations_df = pd.read_sql_query(query1, conn)
table = tabulate(premium_locations_df
    ,
    headers='keys',
    tablefmt='pipe'
)
print(table)

|    | location              |   avg_rating |   total_restaurants |   avg_cost |
|---:|:----------------------|-------------:|--------------------:|-----------:|
|  0 | Lavelle Road          |         4.19 |                 442 |       1427 |
|  1 | Koramangala 5th Block |         4.15 |                1782 |        778 |
|  2 | St. Marks Road        |         4.1  |                 304 |        918 |
|  3 | Koramangala 3rd Block |         4.1  |                 161 |        925 |
|  4 | Cunningham Road       |         4.1  |                 333 |        956 |
|  5 | Koramangala 2nd Block |         4.07 |                  45 |        753 |
|  6 | Sadashiv Nagar        |         4.06 |                  38 |        950 |
|  7 | Residency Road        |         4.05 |                 440 |       1091 |
|  8 | Church Street         |         4.05 |                 506 |        856 |
|  9 | Koramangala 4th Block |         4.04 |                 644 |        836 |

2.Which locations are over-saturated with restaurants?

In [ ]:
query2 = """
SELECT
    location,
    COUNT(*) AS restaurant_count,
    ROUND(AVG(rate), 2) AS avg_rating,
    ROUND(AVG( approx_cost_for_two), 0) AS avg_cost
FROM restaurants1
GROUP BY location
ORDER BY restaurant_count DESC
LIMIT 10;
"""
saturation_df = pd.read_sql(query2, conn)
table = tabulate(saturation_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+-----------------------+--------------------+--------------+------------+
|    | location              |   restaurant_count |   avg_rating |   avg_cost |
+====+=======================+====================+==============+============+
|  0 | Koramangala 5th Block |               1782 |         4.15 |        778 |
+----+-----------------------+--------------------+--------------+------------+
|  1 | BTM                   |               1454 |         3.76 |        503 |
+----+-----------------------+--------------------+--------------+------------+
|  2 | Indiranagar           |               1346 |         3.96 |        783 |
+----+-----------------------+--------------------+--------------+------------+
|  3 | HSR                   |               1161 |         3.84 |        584 |
+----+-----------------------+--------------------+--------------+------------+
|  4 | Jayanagar             |               1037 |         3.94 |        597 |
+----+-----------------------+--------------------+--------------+------------+
|  5 | JP Nagar              |               1016 |         3.86 |        682 |
+----+-----------------------+--------------------+--------------+------------+
|  6 | Whitefield            |                824 |         3.82 |        851 |
+----+-----------------------+--------------------+--------------+------------+
|  7 | Koramangala 7th Block |                723 |         3.99 |        693 |
+----+-----------------------+--------------------+--------------+------------+
|  8 | Koramangala 6th Block |                718 |         3.95 |        703 |
+----+-----------------------+--------------------+--------------+------------+
|  9 | Marathahalli          |                680 |         3.73 |        708 |
+----+-----------------------+--------------------+--------------+------------+

3.Does online ordering improve restaurant ratings?

In [ ]:
query3 = """
SELECT
    online_order,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_outlets,
    ROUND(AVG(votes), 0) AS avg_votes
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY online_order;
"""

online_order_roi_df = pd.read_sql_query(query3, conn)

table = tabulate(online_order_roi_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+----------------+--------------+-----------------+-------------+
|    | online_order   |   avg_rating |   total_outlets |   avg_votes |
+====+================+==============+=================+=============+
|  0 | No             |         3.93 |            6823 |         734 |
+----+----------------+--------------+-----------------+-------------+
|  1 | Yes            |         3.89 |           16335 |         544 |
+----+----------------+--------------+-----------------+-------------+


4.Does table booking correlate with higher customer ratings?

In [ ]:
query4 = """
SELECT
    book_table,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_restaurants
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY book_table;
"""
booking_impact_df = pd.read_sql_query(query4, conn)

table = tabulate(booking_impact_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+--------------+--------------+---------------------+
|    | book_table   |   avg_rating |   total_restaurants |
+====+==============+==============+=====================+
|  0 | No           |         3.81 |               17057 |
+----+--------------+--------------+---------------------+
|  1 | Yes          |         4.16 |                6101 |
+----+--------------+--------------+---------------------+

5.What price range delivers the best customer satisfaction?

In [ ]:
query5 = """
SELECT
    CASE
        WHEN approx_cost_for_two <= 500 THEN 'Budget (0-500)'
        WHEN approx_cost_for_two <= 1000 THEN 'Mid-Range (501-1000)'
        WHEN approx_cost_for_two <= 2000 THEN 'Premium (1001-2000)'
        ELSE 'Luxury (2000+)'
    END AS price_segment,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS restaurant_count,
    ROUND(AVG(votes), 0) AS avg_engagement
FROM restaurants1
WHERE rate IS NOT NULL AND approx_cost_for_two IS NOT NULL
GROUP BY price_segment
ORDER BY avg_rating DESC;
"""
pricing_strategy_df = pd.read_sql_query(query5, conn)

table = tabulate(pricing_strategy_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+----------------------+--------------+--------------------+------------------+
|    | price_segment        |   avg_rating |   restaurant_count |   avg_engagement |
+====+======================+==============+====================+==================+
|  0 | Luxury (2000+)       |         4.2  |                537 |              925 |
+----+----------------------+--------------+--------------------+------------------+
|  1 | Premium (1001-2000)  |         4.17 |               4203 |             1358 |
+----+----------------------+--------------+--------------------+------------------+
|  2 | Mid-Range (501-1000) |         3.89 |               8643 |              627 |
+----+----------------------+--------------+--------------------+------------------+
|  3 | Budget (0-500)       |         3.79 |               9775 |              233 |
+----+----------------------+--------------+--------------------+------------------+

6.How do low, mid, and premium-priced restaurants perform in terms of ratings?

In [ ]:
query6 = """
SELECT
    CASE
        WHEN approx_cost_for_two < 500 THEN 'Low-Priced (<500)'
        WHEN approx_cost_for_two BETWEEN 500 AND 1500 THEN 'Mid-Range (500-1500)'
        ELSE 'Premium (>1500)'
    END AS price_tier,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_restaurants,
    SUM(votes) AS total_customer_engagement
FROM restaurants1
WHERE rate IS NOT NULL AND approx_cost_for_two IS NOT NULL
GROUP BY price_tier
ORDER BY avg_rating DESC;
"""

segmentation_df = pd.read_sql_query(query6, conn)

table = tabulate(segmentation_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+----------------------+--------------+---------------------+-----------------------------+
|    | price_tier           |   avg_rating |   total_restaurants |   total_customer_engagement |
+====+======================+==============+=====================+=============================+
|  0 | Premium (>1500)      |         4.23 |                1554 |                     2186036 |
+----+----------------------+--------------+---------------------+-----------------------------+
|  1 | Mid-Range (500-1500) |         3.92 |               14099 |                    10094563 |
+----+----------------------+--------------+---------------------+-----------------------------+
|  2 | Low-Priced (<500)    |         3.8  |                7505 |                     1620920 |
+----+----------------------+--------------+---------------------+-----------------------------+

7.Which cuisines are most common in Bangalore?

In [ ]:
query7 = """
SELECT
    cuisines,
    COUNT(*) AS total_outlets,
    ROUND(AVG(rate), 2) AS avg_rating,
    ROUND(AVG(approx_cost_for_two), 0) AS avg_cost
FROM restaurants1
WHERE cuisines IS NOT NULL
GROUP BY cuisines
ORDER BY total_outlets DESC
LIMIT 10;
"""

common_cuisines_df = pd.read_sql_query(query7, conn)

table = tabulate(common_cuisines_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+-------------------------------------+-----------------+--------------+------------+
|    | cuisines                            |   total_outlets |   avg_rating |   avg_cost |
+====+=====================================+=================+==============+============+
|  0 | North Indian                        |            1144 |         3.76 |        648 |
+----+-------------------------------------+-----------------+--------------+------------+
|  1 | North Indian, Chinese               |             776 |         3.55 |        607 |
+----+-------------------------------------+-----------------+--------------+------------+
|  2 | South Indian                        |             359 |         3.97 |        329 |
+----+-------------------------------------+-----------------+--------------+------------+
|  3 | Cafe                                |             273 |         3.8  |        587 |
+----+-------------------------------------+-----------------+--------------+------------+
|  4 | South Indian, North Indian, Chinese |             233 |         3.64 |        371 |
+----+-------------------------------------+-----------------+--------------+------------+
|  5 | Bakery, Desserts                    |             215 |         3.91 |        453 |
+----+-------------------------------------+-----------------+--------------+------------+
|  6 | Desserts, Beverages                 |             214 |         4.13 |        409 |
+----+-------------------------------------+-----------------+--------------+------------+
|  7 | Chinese                             |             210 |         3.82 |        998 |
+----+-------------------------------------+-----------------+--------------+------------+
|  8 | Ice Cream, Desserts                 |             208 |         4.13 |        368 |
+----+-------------------------------------+-----------------+--------------+------------+
|  9 | Desserts                            |             206 |         4.12 |        400 |
+----+-------------------------------------+-----------------+--------------+------------+

8.Which cuisines receive the highest average ratings?

In [ ]:
query8 = """
SELECT
    cuisines,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_restaurants
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY cuisines
HAVING total_restaurants >= 30
ORDER BY avg_rating DESC
LIMIT 10;
"""

top_rated_cuisines_df = pd.read_sql_query(query8, conn)
table = tabulate(top_rated_cuisines_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+-----------------------------------------------------+--------------+---------------------+
|    | cuisines                                            |   avg_rating |   total_restaurants |
+====+=====================================================+==============+=====================+
|  0 | North Indian, Thai, Japanese, Continental, Cafe     |         4.69 |                  34 |
+----+-----------------------------------------------------+--------------+---------------------+
|  1 | Cafe, American, Burger, Steak                       |         4.6  |                  43 |
+----+-----------------------------------------------------+--------------+---------------------+
|  2 | North Indian, European, Mediterranean, Bbq, Kebab   |         4.53 |                  39 |
+----+-----------------------------------------------------+--------------+---------------------+
|  3 | Ice Cream, Cafe, Pizza, Burger, Desserts, Beverages |         4.42 |                  33 |
+----+-----------------------------------------------------+--------------+---------------------+
|  4 | Pizza, Cafe, Italian                                |         4.41 |                  85 |
+----+-----------------------------------------------------+--------------+---------------------+
|  5 | Italian, Salad                                      |         4.41 |                  40 |
+----+-----------------------------------------------------+--------------+---------------------+
|  6 | Modern Indian                                       |         4.39 |                  64 |
+----+-----------------------------------------------------+--------------+---------------------+
|  7 | Bakery, Cafe, Italian, Desserts                     |         4.33 |                  30 |
+----+-----------------------------------------------------+--------------+---------------------+
|  8 | Japanese                                            |         4.32 |                  41 |
+----+-----------------------------------------------------+--------------+---------------------+
|  9 | Italian                                             |         4.28 |                  37 |
+----+-----------------------------------------------------+--------------+---------------------+


9.Which cuisines perform well despite having fewer restaurants?

In [ ]:
query9 = """
SELECT
    cuisines,
    AVG(rate) AS avg_rating,
    COUNT(*) AS outlet_count
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY cuisines
HAVING outlet_count BETWEEN 5 AND 50
ORDER BY avg_rating DESC
LIMIT 10;
"""

niche_cuisines_df = pd.read_sql_query(query9, conn)
table = tabulate(niche_cuisines_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+---------------------------------------------------------------+--------------+----------------+
|    | cuisines                                                      |   avg_rating |   outlet_count |
+====+===============================================================+==============+================+
|  0 | Asian, Chinese, Thai, Momos                                   |      4.9     |             19 |
+----+---------------------------------------------------------------+--------------+----------------+
|  1 | Continental, North Indian, Italian, South Indian, Finger Food |      4.9     |              6 |
+----+---------------------------------------------------------------+--------------+----------------+
|  2 | North Indian, European, Mediterranean, Bbq                    |      4.8     |              5 |
+----+---------------------------------------------------------------+--------------+----------------+
|  3 | Asian, Mediterranean, North Indian, Bbq                       |      4.8     |              6 |
+----+---------------------------------------------------------------+--------------+----------------+
|  4 | European, Mediterranean, North Indian, Bbq                    |      4.78947 |             19 |
+----+---------------------------------------------------------------+--------------+----------------+
|  5 | American, Tex-Mex, Burger, Bbq, Mexican                       |      4.75    |              8 |
+----+---------------------------------------------------------------+--------------+----------------+
|  6 | Continental, Asian, North Indian                              |      4.72381 |             21 |
+----+---------------------------------------------------------------+--------------+----------------+
|  7 | North Indian, European, Mediterranean                         |      4.7     |             13 |
+----+---------------------------------------------------------------+--------------+----------------+
|  8 | Continental, European, Bbq, Chinese, Asian                    |      4.7     |              5 |
+----+---------------------------------------------------------------+--------------+----------------+
|  9 | Chinese, American, Continental, Italian, North Indian         |      4.7     |              5 |
+----+---------------------------------------------------------------+--------------+----------------+


10.What is the relationship between restaurant cost and rating?

In [ ]:
query10 = """
SELECT
    CASE
        WHEN approx_cost_for_two < 500 THEN 'Budget (<500)'
        WHEN approx_cost_for_two BETWEEN 500 AND 1500 THEN 'Mid-Range (500-1500)'
        ELSE 'Premium (>1500)'
    END AS price_tier,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS total_restaurants,
    SUM(votes) AS total_votes
FROM restaurants1
WHERE rate IS NOT NULL AND approx_cost_for_two IS NOT NULL
GROUP BY price_tier
ORDER BY avg_rating DESC;
"""
cost_rating_df = pd.read_sql_query(query10, conn)
table = tabulate(cost_rating_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+----------------------+--------------+---------------------+---------------+
|    | price_tier           |   avg_rating |   total_restaurants |   total_votes |
+====+======================+==============+=====================+===============+
|  0 | Premium (>1500)      |         4.23 |                1554 |       2186036 |
+----+----------------------+--------------+---------------------+---------------+
|  1 | Mid-Range (500-1500) |         3.92 |               14099 |      10094563 |
+----+----------------------+--------------+---------------------+---------------+
|  2 | Budget (<500)        |         3.8  |                7505 |       1620920 |
+----+----------------------+--------------+---------------------+---------------+

11.Which locations are ideal for premium restaurant onboarding?

In [ ]:
query11 = """
SELECT
    location,
    AVG(approx_cost_for_two) as avg_cost,
    AVG(rate) as avg_rating,
    COUNT(*) as total_restaurants
FROM restaurants1
WHERE rate IS NOT NULL AND approx_cost_for_two > 1500
GROUP BY location
HAVING total_restaurants > 5
ORDER BY avg_cost DESC, avg_rating DESC;
"""

premium_targets_df = pd.read_sql_query(query11, conn)
table = tabulate(premium_targets_df
    ,
    headers='keys',
    tablefmt='pipe'
)
print(table)

|    | location              |   avg_cost |   avg_rating |   total_restaurants |
|---:|:----------------------|-----------:|-------------:|--------------------:|
|  0 | Sankey Road           |    3228.57 |      4.11429 |                  14 |
|  1 | Seshadripuram         |    2811.11 |      3.98889 |                   9 |
|  2 | Vasanth Nagar         |    2730.77 |      4.21538 |                  13 |
|  3 | Old Airport Road      |    2615    |      4.1525  |                  40 |
|  4 | Residency Road        |    2588.89 |      4.18586 |                  99 |
|  5 | MG Road               |    2353.39 |      4.15127 |                 236 |
|  6 | Race Course Road      |    2352.63 |      4.01053 |                  19 |
|  7 | Richmond Road         |    2339.47 |      4.20789 |                  76 |
|  8 | Marathahalli          |    2270.97 |      4.27742 |                  31 |
|  9 | Infantry Road         |    2254.55 |      4.24545 |                  22 |
| 10 | Ulsoor                |    2231.43 |      4.1819  |                 105 |
| 11 | Basavanagudi          |    2200    |      3.7     |                   6 |
| 12 | Lavelle Road          |    2198.65 |      4.24932 |                 148 |
| 13 | Electronic City       |    2166.67 |      3.98    |                  15 |
| 14 | Malleshwaram          |    2092.86 |      4.25714 |                  28 |
| 15 | Koramangala 6th Block |    2034.04 |      4.01915 |                  47 |
| 16 | Koramangala 3rd Block |    2000    |      4.1     |                  10 |
| 17 | St. Marks Road        |    1975    |      4.47917 |                  48 |
| 18 | Whitefield            |    1973.79 |      4.26505 |                 103 |
| 19 | Brigade Road          |    1883.08 |      4.18    |                  65 |
| 20 | Koramangala 5th Block |    1864.91 |      4.51579 |                  57 |
| 21 | Domlur                |    1861.22 |      4.07755 |                  49 |
| 22 | Sarjapur Road         |    1806.25 |      4.43438 |                  32 |
| 23 | HSR                   |    1800    |      4.2     |                   6 |
| 24 | Bellandur             |    1797.14 |      4.22    |                  35 |
| 25 | Indiranagar           |    1790.54 |      4.26081 |                  74 |
| 26 | Kalyan Nagar          |    1781.82 |      4.29091 |                  11 |
| 27 | Cunningham Road       |    1747.22 |      4.01111 |                  36 |
| 28 | Koramangala 4th Block |    1741.67 |      4.325   |                  24 |
| 29 | Church Street         |    1700    |      4.5     |                  19 |
| 30 | Rajajinagar           |    1681.82 |      4.25455 |                  11 |
| 31 | Koramangala 1st Block |    1600    |      4.7     |                   7 |
| 32 | BTM                   |    1600    |      4.60833 |                  12 |
| 33 | Koramangala 7th Block |    1600    |      4.52308 |                  13 |
| 34 | JP Nagar              |    1600    |      4.495   |                  20 |


12.Which locations show high demand but lower average ratings?

In [ ]:
query12 = """
SELECT
    location,
    ROUND(AVG(rate), 2) AS avg_rating,
    SUM(votes) AS total_votes,
    COUNT(*) AS restaurant_count
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY location
HAVING total_votes > 10000 AND avg_rating < 3.8
ORDER BY total_votes DESC;
"""

quality_gap_df = pd.read_sql_query(query12, conn)

table = tabulate(quality_gap_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+--------------------+--------------+---------------+--------------------+
|    | location           |   avg_rating |   total_votes |   restaurant_count |
+====+====================+==============+===============+====================+
|  0 | BTM                |         3.76 |        473389 |               1454 |
+----+--------------------+--------------+---------------+--------------------+
|  1 | Marathahalli       |         3.73 |        414801 |                680 |
+----+--------------------+--------------+---------------+--------------------+
|  2 | Bannerghatta Road  |         3.68 |        190726 |                496 |
+----+--------------------+--------------+---------------+--------------------+
|  3 | Bellandur          |         3.69 |        188257 |                462 |
+----+--------------------+--------------+---------------+--------------------+
|  4 | Brookefield        |         3.7  |        112476 |                307 |
+----+--------------------+--------------+---------------+--------------------+
|  5 | Electronic City    |         3.7  |         96667 |                326 |
+----+--------------------+--------------+---------------+--------------------+
|  6 | Domlur             |         3.69 |         92542 |                206 |
+----+--------------------+--------------+---------------+--------------------+
|  7 | Shanti Nagar       |         3.66 |         50925 |                166 |
+----+--------------------+--------------+---------------+--------------------+
|  8 | Jeevan Bhima Nagar |         3.68 |         43259 |                174 |
+----+--------------------+--------------+---------------+--------------------+
|  9 | Banaswadi          |         3.64 |         28358 |                195 |
+----+--------------------+--------------+---------------+--------------------+
| 10 | Commercial Street  |         3.69 |         23688 |                141 |
+----+--------------------+--------------+---------------+--------------------+
| 11 | Nagawara           |         3.67 |         15686 |                 62 |
+----+--------------------+--------------+---------------+--------------------+
| 12 | Ejipura            |         3.75 |         12928 |                 58 |
+----+--------------------+--------------+---------------+--------------------+
| 13 | Kumaraswamy Layout |         3.62 |         12599 |                 56 |
+----+--------------------+--------------+---------------+--------------------+

13.Do restaurants offering both online ordering and table booking perform better?

In [ ]:
query13 = """
SELECT
    online_order,
    book_table,
    ROUND(AVG(rate), 2) AS avg_rating,
    COUNT(*) AS restaurant_count,
    ROUND(AVG(votes), 0) AS avg_engagement
FROM restaurants1
WHERE rate IS NOT NULL
GROUP BY online_order, book_table
ORDER BY avg_rating DESC;
"""
bundle_performance_df = pd.read_sql_query(query13, conn)
table = tabulate(bundle_performance_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+----------------+--------------+--------------+--------------------+------------------+
|    | online_order   | book_table   |   avg_rating |   restaurant_count |   avg_engagement |
+====+================+==============+==============+====================+==================+
|  0 | No             | Yes          |         4.18 |               2468 |             1193 |
+----+----------------+--------------+--------------+--------------------+------------------+
|  1 | Yes            | Yes          |         4.14 |               3633 |             1203 |
+----+----------------+--------------+--------------+--------------------+------------------+
|  2 | Yes            | No           |         3.82 |              12702 |              356 |
+----+----------------+--------------+--------------+--------------------+------------------+
|  3 | No             | No           |         3.79 |               4355 |              474 |
+----+----------------+--------------+--------------+--------------------+------------------+

14.What combination of factors maximizes restaurant success on Uber Eats?

In [ ]:
query14 = """
SELECT
    restaurant_name,
    location,
    cuisines,
    rate,
    votes,
    approx_cost_for_two
FROM restaurants1
WHERE online_order = 'Yes'
  AND book_table = 'Yes'
  AND rate >= 4.5
ORDER BY votes DESC
LIMIT 10;
"""

power_partners_df = pd.read_sql_query(query14, conn)
table = tabulate(power_partners_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|    | restaurant_name              | location      | cuisines                                                      |   rate |   votes |   approx_cost_for_two |
+====+==============================+===============+===============================================================+========+=========+=======================+
|  0 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16832 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  1 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16832 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  2 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16832 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  3 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16345 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  4 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16345 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  5 | Byg Brewski Brewing Company  | Sarjapur Road | Continental, North Indian, Italian, South Indian, Finger Food |    4.9 |   16345 |                  1600 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  6 | Chili's American Grill & Bar | Malleshwaram  | American, Tex-Mex, Burger, Bbq, Mexican                       |    4.8 |    6470 |                  1400 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  7 | Chili's American Grill & Bar | Malleshwaram  | American, Tex-Mex, Burger, Bbq, Mexican                       |    4.8 |    6470 |                  1400 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  8 | Chili's American Grill & Bar | Malleshwaram  | American, Tex-Mex, Burger, Bbq, Mexican                       |    4.8 |    6461 |                  1400 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+
|  9 | Chili's American Grill & Bar | Malleshwaram  | American, Tex-Mex, Burger, Bbq, Mexican                       |    4.8 |    6440 |                  1400 |
+----+------------------------------+---------------+---------------------------------------------------------------+--------+---------+-----------------------+


15.Which restaurants are top performers within each pricing segment?

In [ ]:
query15 = """
WITH PriceSegments AS (
    SELECT
        restaurant_name,
        location,
        cuisines,
        rate,
        votes,
        approx_cost_for_two,
        CASE
            WHEN approx_cost_for_two <= 500 THEN 'Budget'
            WHEN approx_cost_for_two <= 1000 THEN 'Mid-Range'
            WHEN approx_cost_for_two <= 2000 THEN 'Premium'
            ELSE 'Luxury'
        END AS price_segment
    FROM restaurants1
    WHERE rate IS NOT NULL
)
SELECT * FROM (
    SELECT *,
           RANK() OVER (PARTITION BY price_segment ORDER BY rate DESC, votes DESC) as rank
    FROM PriceSegments
)
WHERE rank <= 3;
"""
benchmark_partners_df = pd.read_sql_query(query15, conn)
table = tabulate(benchmark_partners_df
    ,
    headers='keys',
    tablefmt='grid'
)
print(table)

+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|    | restaurant_name             | location              | cuisines                                                              |   rate |   votes |   approx_cost_for_two | price_segment   |   rank |
+====+=============================+=======================+=======================================================================+========+=========+=======================+=================+========+
|  0 | Milano Ice Cream            | Indiranagar           | Ice Cream, Desserts                                                   |    4.9 |    2090 |                   400 | Budget          |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  1 | Belgian Waffle Factory      | Brigade Road          | Desserts                                                              |    4.9 |    1750 |                   400 | Budget          |      2 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  2 | Belgian Waffle Factory      | Brigade Road          | Desserts                                                              |    4.9 |    1750 |                   400 | Budget          |      2 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  3 | Biergarten                  | Koramangala 5th Block | Continental, North Indian, Chinese, European, Bbq, Finger Food, Asian |    4.8 |     524 |                  2100 | Luxury          |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  4 | Biergarten                  | Koramangala 5th Block | Continental, North Indian, Chinese, European, Bbq, Finger Food, Asian |    4.8 |     516 |                  2100 | Luxury          |      2 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  5 | Biergarten                  | Koramangala 5th Block | Continental, North Indian, Chinese, European, Bbq, Finger Food, Asian |    4.8 |     516 |                  2100 | Luxury          |      2 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  6 | SantÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ© Spa Cuisine                             | Indiranagar           | Healthy Food, Salad, Mediterranean                                    |    4.9 |     246 |                  1000 | Mid-Range       |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  7 | House Of Commons            | Koramangala 5th Block | Continental, Asian, North Indian                                      |    4.8 |    4441 |                  1000 | Mid-Range       |      2 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  8 | House Of Commons            | Koramangala 5th Block | Continental, Asian, North Indian                                      |    4.8 |    4390 |                  1000 | Mid-Range       |      3 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
|  9 | House Of Commons            | Koramangala 5th Block | Continental, Asian, North Indian                                      |    4.8 |    4390 |                  1000 | Mid-Range       |      3 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
| 10 | House Of Commons            | Koramangala 5th Block | Continental, Asian, North Indian                                      |    4.8 |    4390 |                  1000 | Mid-Range       |      3 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
| 11 | House Of Commons            | Koramangala 5th Block | Continental, Asian, North Indian                                      |    4.8 |    4390 |                  1000 | Mid-Range       |      3 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
| 12 | Byg Brewski Brewing Company | Sarjapur Road         | Continental, North Indian, Italian, South Indian, Finger Food         |    4.9 |   16832 |                  1600 | Premium         |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
| 13 | Byg Brewski Brewing Company | Sarjapur Road         | Continental, North Indian, Italian, South Indian, Finger Food         |    4.9 |   16832 |                  1600 | Premium         |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+
| 14 | Byg Brewski Brewing Company | Sarjapur Road         | Continental, North Indian, Italian, South Indian, Finger Food         |    4.9 |   16832 |                  1600 | Premium         |      1 |
+----+-----------------------------+-----------------------+-----------------------------------------------------------------------+--------+---------+-----------------------+-----------------+--------+

**ORDER DATASET**

In [ ]:
import json

In [ ]:
df=pd.read_json('/content/drive/MyDrive/Colab Notebooks/orders.json')

In [ ]:
df

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551,Yes,UPI
...,...,...,...,...,...,...
24995,74d3cd31-c1e0-4331-aad7-e1f48b4698ae,Carnatic,2025-11-24,1254,No,UPI
24996,14db2f6b-f722-44a2-ae55-fe42511e4bb2,Reddy's Restaurant,2025-06-24,760,No,Card
24997,0fd85321-c1ce-4163-beca-c8ed2b472b8d,BTM Bawarchi Biryani,2025-12-04,707,Yes,Card
24998,6b96c699-2d63-4a3c-84f1-5d52ca4bf357,Nite Out,2025-09-21,724,Yes,Card
24999,af55e28b-27fc-49fc-bdb0-b297999dd152,Zee5 Loft,2025-08-07,905,No,UPI

In [ ]:
df.shape

(25000, 6)

In [ ]:
df.columns

Index(['order_id', 'restaurant_name', 'order_date', 'order_value',
       'discount_used', 'payment_method'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  object
 3   order_value      25000 non-null  int64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: int64(1), object(5)
memory usage: 1.1+ MB

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         25000 non-null  object
 1   restaurant_name  25000 non-null  object
 2   order_date       25000 non-null  datetime64[ns]
 3   order_value      25000 non-null  int64
 4   discount_used    25000 non-null  object
 5   payment_method   25000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(4)
memory usage: 1.1+ MB

**cleaned data**

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cleaned order_data (1).csv')

In [ ]:
df

,order_id,restaurant_name,order_date,order_value,discount_used,payment_method
0,8174c2af-07a4-4837-9068-1169d963e36e,TBC Sky Lounge,2025-05-06,201,No,Card
1,0f9ddb57-4632-4a9f-9afe-1d2e41b94e32,KC Das - Sweet Paradise,2026-01-08,1392,No,Cash
2,099deda6-8c53-41cb-abf8-00126e6b2643,Hotel Kadamba Veg,2026-01-22,1358,Yes,UPI
3,94a6ba27-d6ef-4d10-a026-ac0c0afa8505,Cafe Srinidhi,2025-11-10,782,No,UPI
4,216f3ec7-80a9-4d95-872f-715c37163b6d,Pebble,2025-12-22,1551,Yes,UPI
...,...,...,...,...,...,...
24995,74d3cd31-c1e0-4331-aad7-e1f48b4698ae,Carnatic,2025-11-24,1254,No,UPI
24996,14db2f6b-f722-44a2-ae55-fe42511e4bb2,Reddy's Restaurant,2025-06-24,760,No,Card
24997,0fd85321-c1ce-4163-beca-c8ed2b472b8d,BTM Bawarchi Biryani,2025-12-04,707,Yes,Card
24998,6b96c699-2d63-4a3c-84f1-5d52ca4bf357,Nite Out,2025-09-21,724,Yes,Card
24999,af55e28b-27fc-49fc-bdb0-b297999dd152,Zee5 Loft,2025-08-07,905,No,UPI

In [ ]:
conn = sqlite3.connect('restaurant1.db')
cursor = conn.cursor()

# 2. Wrap the SQL command in a string using triple quotes
create_table_query = """
CREATE TABLE IF NOT EXISTS orders (
    order_id TEXT PRIMARY KEY,
    restaurant_name TEXT,
    order_date DATE,
    order_value INTEGER,
    discount_used TEXT,
    payment_method TEXT
);
"""

# 3. Execute the string
cursor.execute(create_table_query)

# 4. Commit and close
conn.commit()
print("Table created successfully!")

Table created successfully!

In [ ]:
data_list = df.values.tolist()

In [ ]:
insert_query = """
INSERT INTO orders (order_id, restaurant_name, order_date, order_value, discount_used, payment_method)
VALUES (?, ?, ?, ?, ?, ?);
"""

cursor.executemany(insert_query, data_list)

In [ ]:
conn.commit()

In [ ]:
cursor.execute("SELECT COUNT(*) FROM orders;")
count = cursor.fetchone()[0]

print(f"Total rows in table: {count}")

Total rows in table: 25000

1. What is the total revenue generated across all restaurants in the dataset?

In [ ]:
query1 = """
SELECT
    SUM(order_value) AS total_revenue,
    COUNT(order_id) AS total_orders,
    ROUND(AVG(order_value), 2) AS avg_order_value
FROM orders;
"""
revenue_df = pd.read_sql_query(query1, conn)
table = tabulate(
    revenue_df,
    headers='keys',
    tablefmt='pipe',
    showindex=False
)

print(table)

|   total_revenue |   total_orders |   avg_order_value |
|----------------:|---------------:|------------------:|
|     2.46396e+07 |          25000 |            985.59 |

2.Does using a discount significantly increase the average order value (AOV)?

In [ ]:
query2 = """
SELECT
    discount_used,
    ROUND(AVG(order_value), 2) AS average_order_value,
    COUNT(*) AS total_orders,
    SUM(order_value) AS total_revenue
FROM orders
GROUP BY discount_used;
"""
discount_efficiency_df = pd.read_sql_query(query2, conn)
table = tabulate(
    discount_efficiency_df,
    headers='keys',
    tablefmt='pipe',
    showindex=False
)

print(table)

| discount_used   |   average_order_value |   total_orders |   total_revenue |
|:----------------|----------------------:|---------------:|----------------:|
| No              |                821.99 |          12509 |        10282311 |
| Yes             |               1149.41 |          12491 |        14357322 |

 3.Which payment method is most frequently used by customers?

In [ ]:
query3 = """
SELECT
    payment_method,
    COUNT(*) AS total_transactions,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS usage_percentage
FROM orders
GROUP BY payment_method
ORDER BY total_transactions DESC;
"""

# Executing the query
payment_methods_df = pd.read_sql_query(query3, conn)

# Formatting the output
table = tabulate(
    payment_methods_df,
    headers='keys',
    tablefmt='pipe',
    showindex=False
)

print(table)

| payment_method   |   total_transactions |   usage_percentage |
|:-----------------|---------------------:|-------------------:|
| Cash             |                 8384 |              33.54 |
| Card             |                 8364 |              33.46 |
| UPI              |                 8252 |              33.01 |

4.Are there specific months or seasons where order volume spikes?

In [ ]:
query4 = """
SELECT
    STRFTIME('%Y-%m', order_date) AS month,
    COUNT(order_id) AS total_orders,
    SUM(order_value) AS monthly_revenue
FROM orders
GROUP BY month
ORDER BY month ASC;
"""

# Executing the query
seasonal_trends_df = pd.read_sql_query(query4, conn)

# Formatting the output
table = tabulate(
    seasonal_trends_df,
    headers='keys',
    tablefmt='pipe',
    showindex=False
)

print(table)

| month   |   total_orders |   monthly_revenue |
|:--------|---------------:|------------------:|
| 2025-04 |            152 |            150906 |
| 2025-05 |           2592 |           2572617 |
| 2025-06 |           2422 |           2372938 |
| 2025-07 |           2613 |           2566475 |
| 2025-08 |           2520 |           2443636 |
| 2025-09 |           2483 |           2447850 |
| 2025-10 |           2531 |           2525919 |
| 2025-11 |           2478 |           2450568 |
| 2025-12 |           2664 |           2579243 |
| 2026-01 |           2642 |           2629436 |
| 2026-02 |           1903 |           1900045 |

5. Which restaurant brand is contributing the most to total sales volume?

In [ ]:
query5 = """
SELECT
    restaurant_name,
    SUM(order_value) AS total_sales_volume,
    COUNT(order_id) AS order_count,
    ROUND(AVG(order_value), 2) AS avg_order_value
FROM orders
GROUP BY restaurant_name
ORDER BY total_sales_volume DESC
LIMIT 10;
"""

top_restaurants_df = pd.read_sql_query(query5, conn)

table = tabulate(
    top_restaurants_df,
    headers='keys',
    tablefmt='pipe',
    showindex=False
)

print(table)

| restaurant_name     |   total_sales_volume |   order_count |   avg_order_value |
|:--------------------|---------------------:|--------------:|------------------:|
| Bob's Bar           |                19511 |            15 |           1300.73 |
| Cake Cafe           |                19324 |            19 |           1017.05 |
| Biryani Mane        |                19243 |            15 |           1282.87 |
| Hungry Lee          |                19158 |            18 |           1064.33 |
| Andhra Grills       |                19146 |            19 |           1007.68 |
| Mighty Paws         |                18399 |            17 |           1082.29 |
| Delhi Ke Bawarchi   |                18124 |            15 |           1208.27 |
| Pingara             |                17948 |            15 |           1196.53 |
| Bawarchi Inn        |                17710 |            15 |           1180.67 |
| Soup'ermanz Kitchen |                17343 |            13 |           1334.08 |

6.What is the typical spend per order?

In [ ]:
query6 = """
SELECT
    ROUND(AVG(order_value), 2) AS atv,
    MIN(order_value) AS min_order,
    MAX(order_value) AS max_order
FROM orders;
"""
df6 = pd.read_sql_query(query6, conn)
print(tabulate(df6, headers='keys', tablefmt='pipe', showindex=False))

|    atv |   min_order |   max_order |
|-------:|------------:|------------:|
| 985.59 |         150 |        1999 |

7.What percentage of total orders utilize a discount code?

In [ ]:
query7 = """
SELECT
    discount_used,
    COUNT(*) AS order_count,
    ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM orders), 2) AS penetration_percentage
FROM orders
GROUP BY discount_used;
"""
df7 = pd.read_sql_query(query7, conn)
print(tabulate(df7, headers='keys', tablefmt='pipe', showindex=False))

| discount_used   |   order_count |   penetration_percentage |
|:----------------|--------------:|-------------------------:|
| No              |         12509 |                    50.04 |
| Yes             |         12491 |                    49.96 |

8. Do the top performing restaurants account for the majority of revenue?

In [ ]:
query8 = """
SELECT
    restaurant_name,
    SUM(order_value) AS revenue,
    ROUND(SUM(order_value) * 100.0 / (SELECT SUM(order_value) FROM orders), 2) AS revenue_share_percentage
FROM orders
GROUP BY restaurant_name
ORDER BY revenue DESC
LIMIT 10;
"""
df8 = pd.read_sql_query(query8, conn)
print(tabulate(df8, headers='keys', tablefmt='pipe', showindex=False))

| restaurant_name     |   revenue |   revenue_share_percentage |
|:--------------------|----------:|---------------------------:|
| Bob's Bar           |     19511 |                       0.08 |
| Cake Cafe           |     19324 |                       0.08 |
| Biryani Mane        |     19243 |                       0.08 |
| Hungry Lee          |     19158 |                       0.08 |
| Andhra Grills       |     19146 |                       0.08 |
| Mighty Paws         |     18399 |                       0.07 |
| Delhi Ke Bawarchi   |     18124 |                       0.07 |
| Pingara             |     17948 |                       0.07 |
| Bawarchi Inn        |     17710 |                       0.07 |
| Soup'ermanz Kitchen |     17343 |                       0.07 |

9.Do customers spend more when they pay via Card versus Cash?

In [ ]:
query9 = """
SELECT
    payment_method,
    ROUND(AVG(order_value), 2) AS avg_spend,
    SUM(order_value) AS total_revenue
FROM orders
GROUP BY payment_method
ORDER BY avg_spend DESC;
"""
df9 = pd.read_sql_query(query9, conn)
print(tabulate(df9, headers='keys', tablefmt='pipe', showindex=False))

| payment_method   |   avg_spend |   total_revenue |
|:-----------------|------------:|----------------:|
| Card             |      988.53 |         8268042 |
| UPI              |      985.25 |         8130278 |
| Cash             |      982.98 |         8241313 |

10. What is the volatility (Standard Deviation) of daily sales?

In [ ]:
query10 = """
SELECT
    AVG(daily_total) AS avg_daily_revenue,
    -- Standard Deviation formula (Population)
    SQRT(AVG(daily_total * daily_total) - AVG(daily_total) * AVG(daily_total)) AS daily_volatility
FROM (
    SELECT order_date, SUM(order_value) AS daily_total
    FROM orders
    GROUP BY order_date
);
"""
df10 = pd.read_sql_query(query10, conn)
print(tabulate(df10, headers='keys', tablefmt='pipe', showindex=False))

|   avg_daily_revenue |   daily_volatility |
|--------------------:|-------------------:|
|             81859.2 |            10104.7 |

In [ ]:
!pip install -q streamlit
!npm install -g localtunnel

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.2/9.2 MB 51.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 57.8 MB/s eta 0:00:00
⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙
added 22 packages in 2s
⠙
⠙3 packages are looking for funding
⠙  run `npm fund` for details
⠙

In [ ]:
!pip install pyngrok

Collecting pyngrok
  Downloading pyngrok-8.1.2-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Downloading pyngrok-8.1.2-py3-none-any.whl (25 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-8.1.2

**APPLICATION USING Streamlit**

In [ ]:
%%writefile app.py
import streamlit as st
import sqlite3
import pandas as pd
import os

st.set_page_config(page_title="Uber Eats & Order Analytics", layout="wide")

# Use ONE database name for everything
DB_NAME = 'restaurant1.db'

@st.cache_data
def load_and_prep_all_data():
    # 1. Load Restaurant Data
    try:
        # Update these paths to where your files actually sit
        df_rest = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/restaurantdata (1).csv')
        df_rest.columns = [c.replace(' ', '_').lower() for c in df_rest.columns]

        # 2. Load Order Data
        df_order = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cleaned order_data (1).csv')
        df_order['order_date'] = pd.to_datetime(df_order['order_date'])

        # 3. Save both to the SAME database
        conn = sqlite3.connect('restaurant1.db')
        df_rest.to_sql('restaurants1', conn, index=False, if_exists='replace')
        df_order.to_sql('orders', conn, index=False, if_exists='replace')
        conn.close()

        return df_order
    except Exception as e:
        st.error(f"Error loading data: {e}")
        return pd.DataFrame()

df_orders = load_and_prep_all_data()

# Helper for SQL
def run_sql(query, params=None):
    with sqlite3.connect('restaurant1.db') as conn:
        if params:
            return pd.read_sql_query(query, conn, params=params)
        return pd.read_sql_query(query, conn)

# 3. Sidebar Navigation
st.sidebar.title("🚀 Navigation")
page = st.sidebar.radio("Select Dashboard",
    ["Restaurant Dashboard", "Restaurant Q&A", "Order Dashboard", "Order BI (SQL Queries)"])

# --- PAGE 1: RESTAURANT DASHBOARD ---
if page == "Restaurant Dashboard":
    st.title("🍽️ Bangalore Restaurant Analysis")
    st.sidebar.header("Filters")

    try:
        loc_df = run_sql("SELECT DISTINCT location FROM restaurants1 WHERE location IS NOT NULL")
        locations = ["All"] + sorted(loc_df['location'].tolist())

        selected_loc = st.sidebar.selectbox("Select Location", locations)
        order_online = st.sidebar.radio("Online Order Available?", ["Any", "Yes", "No"])
        max_price = st.sidebar.slider("Max Cost for Two", 0, 5000, 5000)

        # Build Query
        query = "SELECT * FROM restaurants1 WHERE approx_cost_for_two <= ?"
        params = [max_price]

        if selected_loc != "All":
            query += " AND location = ?"
            params.append(selected_loc)

        if order_online != "Any":
            query += " AND online_order = ?"
            params.append(order_online)

        # Execute
        conn = sqlite3.connect('restaurant1.db')
        filtered_df = pd.read_sql_query(query, conn, params=params)
        conn.close()

        if not filtered_df.empty:
            col1, col2, col3 = st.columns(3)
            col1.metric("Total Found", len(filtered_df))
            col2.metric("Avg Rating", round(filtered_df['rate'].mean(), 2))
            col3.metric("Avg Cost", f"₹{int(filtered_df['approx_cost_for_two'].mean())}")

            st.dataframe(filtered_df, use_container_width=True, hide_index=True)
        else:
            st.warning("No restaurants match your filters.")

    except Exception as e:
        st.error(f"Error loading dashboard: {e}")


# --- PAGE 2: RESTAURANT Q&A ---
elif page == "Restaurant Q&A":
    st.title("🔍 Restaurant Business Intelligence")
    q_rest = {
         "1. Highest Rated Locations": "SELECT location, AVG(rate) as avg_rating FROM restaurants1 GROUP BY location ORDER BY avg_rating DESC LIMIT 10",
        "2. Over-saturated Locations": "SELECT location, COUNT(*) as total_restaurants FROM restaurants1 GROUP BY location ORDER BY total_restaurants DESC LIMIT 10",
        "3. Online Order vs Ratings": "SELECT online_order, AVG(rate) as avg_rating FROM restaurants1 GROUP BY online_order",
        "4. Table Booking vs Ratings": "SELECT book_table, AVG(rate) as avg_rating FROM restaurants1 GROUP BY book_table",
        "5. Best Satisfaction Price Range": "SELECT approx_cost_for_two, AVG(rate) as avg_rating FROM restaurants1 GROUP BY approx_cost_for_two ORDER BY avg_rating DESC LIMIT 10",
        "6. Performance by Price Segment": "SELECT CASE WHEN approx_cost_for_two < 500 THEN 'Low' WHEN approx_cost_for_two BETWEEN 500 AND 1500 THEN 'Mid' ELSE 'Premium' END as segment, AVG(rate) as avg_rating FROM restaurants1 GROUP BY segment",
        "7. Most Common Cuisines": "SELECT cuisines, COUNT(*) as count FROM restaurants1 GROUP BY cuisines ORDER BY count DESC LIMIT 10",
        "8. Highest Rated Cuisines": "SELECT cuisines, AVG(rate) as avg_rating FROM restaurants1 GROUP BY cuisines HAVING COUNT(*) > 10 ORDER BY avg_rating DESC LIMIT 10",
        "9. Niche High-Performers": "SELECT cuisines, COUNT(*) as count, AVG(rate) as avg_rating FROM restaurants1 GROUP BY cuisines HAVING count < 5 ORDER BY avg_rating DESC LIMIT 10",
        "10. Cost vs Rating Relationship": "SELECT approx_cost_for_two, AVG(rate) as avg_rating FROM restaurants1 GROUP BY approx_cost_for_two ORDER BY approx_cost_for_two ASC",
        "11. Ideal Locations for Premium Onboarding": "SELECT location, AVG(approx_cost_for_two) as avg_cost, AVG(rate) as avg_rating FROM restaurants1 GROUP BY location HAVING avg_cost > 1000 ORDER BY avg_rating DESC",
        "12. High Demand / Low Rating (Opportunity)": "SELECT location, COUNT(*) as total_orders, AVG(rate) as avg_rating FROM restaurants1 GROUP BY location HAVING total_orders > 100 ORDER BY avg_rating ASC LIMIT 10",
        "13. Dual Service Performance": "SELECT online_order, book_table, AVG(rate) as avg_rating FROM restaurants1 GROUP BY online_order, book_table",
        "14. Success Factors for Delivery": "SELECT online_order, AVG(rate) as avg_rating, SUM(votes) as total_votes FROM restaurants1 GROUP BY online_order",
        "15. Top Performers by Segment": "SELECT name, approx_cost_for_two, rate, location FROM restaurants1 WHERE rate > 4.5 ORDER BY approx_cost_for_two DESC LIMIT 20"
    }
    sel = st.selectbox("Question:", list(q_rest.keys()))
    st.dataframe(run_sql(q_rest[sel]), use_container_width=True)

# --- PAGE 3: ORDER DASHBOARD (Visuals) ---
elif page == "Order Dashboard":
    st.title("Order Dashboard")
    st.sidebar.header("Filters")
    rest_list = df_orders['restaurant_name'].unique()
    selected_res = st.sidebar.multiselect("Restaurants", rest_list, default=rest_list[:5])

    f_df = df_orders[df_orders['restaurant_name'].isin(selected_res)]

    col1, col2 = st.columns(2)
    col1.metric("Total Revenue", f"₹{f_df['order_value'].sum():,.2f}")
    col2.metric("Avg Order", f"₹{f_df['order_value'].mean():.2f}")

    st.subheader("Revenue by Restaurant")
    st.bar_chart(f_df.groupby('restaurant_name')['order_value'].sum())

# --- PAGE 4: ORDER BI (New SQL Queries) ---
elif page == "Order BI (SQL Queries)":
    st.title("💡 Order Insights via SQL")

    queries = {
        "1. Total Revenue": "SELECT SUM(order_value) as result FROM orders",
        "2. Discount vs AOV": "SELECT discount_used, AVG(order_value) as result FROM orders GROUP BY discount_used",
        "3. Most Frequent Payment": "SELECT payment_method, COUNT(*) as result FROM orders GROUP BY payment_method ORDER BY result DESC",
        "4. Monthly Spikes": "SELECT strftime('%m', order_date) as month, COUNT(*) as result FROM orders GROUP BY month ORDER BY month",
        "5. Top Brand by Volume": "SELECT restaurant_name, SUM(order_value) as result FROM orders GROUP BY restaurant_name ORDER BY result DESC LIMIT 10",
        "6. Typical Spend (Avg)": "SELECT AVG(order_value) as result FROM orders",
        "7. Discount Usage %": "SELECT (SUM(CASE WHEN discount_used = 'Yes' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) as result FROM orders",
        "8. Pareto Analysis (Top 5% Revenue)": "SELECT restaurant_name, SUM(order_value) as rev FROM orders GROUP BY restaurant_name ORDER BY rev DESC",
        "9. Card vs Cash AOV": "SELECT payment_method, AVG(order_value) as result FROM orders WHERE payment_method IN ('Card', 'Cash') GROUP BY payment_method",
        "10. Daily Sales Std Dev": """SELECT AVG(daily_sum) as avg_sales,
            (SUM((daily_sum - (SELECT AVG(d_sum) FROM (SELECT SUM(order_value) as d_sum FROM orders GROUP BY order_date))) *
            (daily_sum - (SELECT AVG(d_sum) FROM (SELECT SUM(order_value) as d_sum FROM orders GROUP BY order_date)))) / COUNT(*)) as variance
            FROM (SELECT SUM(order_value) as daily_sum FROM orders GROUP BY order_date)"""
    }
    sel = st.selectbox("Question:", list(queries.keys()))
    st.dataframe(run_sql(queries[sel]), use_container_width=True)

Overwriting app.py

**USING THE BELOW CODE SEE THE OUTPUT OF THE APPLICATION**

In [ ]:
# 1. Get your public IP (copy this output for the tunnel login)
!curl ipv4.icanhazip.com

# 2. Start Streamlit in the background
!streamlit run app.py &>/content/logs.txt &

# 3. Expose the port 8501 to a public URL
!npx localtunnel --port 8501